@startuml
/'AUTOSAR SW layers include: 
- System Services
- Onboard Device Abstraction
- Microcontroller Driver
- Memory Services
- Memory Hardware Abstraction
- Memory Drivers
- Communication Services
- Communication Hardware Abstraction
- Communication Drivers
- I/O Hardware Abstraction
- I/O Drivers
- Complex Drivers'/

/'ASW: application software layer'/
rectangle "ASW" #gray {
[SWC1]
[SWC2]
}

/'RTE: run-time environment layer'/
rectangle "RTE" #gray

/'BSW: basic software layer'/
rectangle "BSW" {
    rectangle "Stack System" {
        rectangle "System Services" #MediumPurple {
            [AUTOSAR OS] /'AUTOSAR operationing system'/
            [Dem] /'Diagnostic Event Manager'/
            [EcuM] /'ECU State Manager'/
            [FiM] /'Function Inhibition Manager'/
            [Det] /'Default Error Tracer'/
            [Dlt] /'Diagnostic Log and Trace'/
            [Csm] /'Crypto Service Manager'/
            [StbM] /'Synchronized Time-Base Manager'/
            [Tm] /'Time Service'/
            [WdgM] /'Watchdog Manager'/
            [ComM] /'COM Manager'/
            [BswM] /'BSW Mode Manager'/
        }
        rectangle "Onboard Device Abstraction" #YellowGreen {
            [WdgIf] /'Watchdog Interface'/
        }
        rectangle "Microcontroller Driver" #Pink {
            [Gpt] /'General Purpose Timer Driver'/
            [Wdg] /'Watchdog Driver'/
            [Mcu] /'Microcontroller Driver'/
            [CorTst] /'Core Test'/
        }

        "System Services" -[hidden]> "Onboard Device Abstraction"
        "System Services" -[hidden]> "Microcontroller Driver"
        "Onboard Device Abstraction" --[hidden]> "Microcontroller Driver"
    }

    "Stack System" -[hidden]> "Memory Stack"

    rectangle "Memory Stack" {
        rectangle "Memory Services" #MediumPurple {
            [NvM] /'NVRAM Manager'/
        }
        rectangle "Memory Hardware Abstraction" #YellowGreen {
            [MemIf] /'Memory Abstraction Interface'/
            [Ea] /'EEPROM Abstraction'/
            [Fee] /'Flash EEPROM Emulation'/
        }    
        rectangle "Memory Drivers" #Pink {
            [FlsTst] /'Flash Test'/
            [RamTst] /'RAM Test'/
            [Fls] /'Flash Driver'/
            [Eep] /'EEPROM Driver'/
        }

        "Memory Services" --[hidden]> "Memory Hardware Abstraction"
        "Memory Hardware Abstraction" ---[hidden]> "Memory Drivers"
    }

    rectangle "Com Stack" {
        rectangle "Communication Services" #MediumPurple {
            [Com] /'Communication'/
            [Dcm] /'Diagnostic Communication Manager'/
            [Dbg] /'debug'/
            [PduR] /'PDU Router'/
            [IpduM] /'IPDU Multiplexer'/
            [SecOC] /'Secure Onboard Communication'/
            [Xf] /'Transformer'/
            [NmIf] /'Network Management Interface'/
            [SM] /'State Manager'/
            [Nm] /'Network Management'/
            [Tp] /'Transport Layer'/
        }
        rectangle "Communication Hardware Abstraction" #YellowGreen {
            [xxx Interface]
            [Trcv] /'Tranceiver Driver'/
            [ext Drv] /'external driver'/
        }
        rectangle "Communication Drivers" #Pink {
            [Spi] /'SPI Handler Driver'/
            [Can] /'CAN Driver'/
            [Lin] /'LIN Driver'/
            [Eth] /'Ethernet Driver'/
            [Fr] /'FlexRay Driver'/
        }

        "Communication Services" ----[hidden]> "Communication Hardware Abstraction"
        "Communication Hardware Abstraction" ---[hidden]> "Communication Drivers"
    }

    "Memory Stack" -[hidden]> "Com Stack"

    rectangle "I/O Stack" {
        rectangle "I/O Hardware Abstraction" #YellowGreen {
            [I/O Signal Interface]
            [Driver for external ADC ASIC]
            [Driver for external I/O ASIC]
        }
        rectangle "I/O Drivers" #Pink {
            [Ocu] /'Output Compare Driver'/
            [Icu] /'Input Capture Unit Driver'/
            [Pwm] /'PWM Driver'/
            [Adc] /'ADC Driver'/
            [Dio] /'Digital Input/Output Driver'/
            [Port] /'Port Driver'/
        }

        "I/O Hardware Abstraction" ---[hidden]> "I/O Drivers"
    }

    "Com Stack" --[hidden]> "I/O Stack"
  
    rectangle "Complex Drivers" {
        [Cdd_1]
    }

    "I/O Stack" -[hidden]> "Complex Drivers"
}

rectangle "MCAL" #gray /'Microcontroller Abstraction Layer'/

ASW --[hidden]> RTE
RTE --[hidden]> BSW
BSW --------[hidden]> MCAL

"Communication Hardware Abstraction" -[hidden]> "I/O Hardware Abstraction"
"Communication Drivers" -[hidden]> "I/O Drivers"

@enduml